static const char portal_html[] =
    "<!DOCTYPE html>\n"
    "<html><head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>Claude Monitor Setup</title>\n"
    "<style>\n"
    "*{box-sizing:border-box}\n"
    "body{font-family:-apple-system,sans-serif;max-width:400px;margin:0 auto;padding:20px;background:#f5f5f5;color:#333}\n"
    "h2{margin:0 0 20px;text-align:center}\n"
    "label{display:block;margin:12px 0 4px;font-weight:600;font-size:14px}\n"
    "select,input,button{width:100%;padding:12px;margin:0 0 4px;border:1px solid #ccc;border-radius:6px;font-size:16px}\n"
    "select:focus,input:focus{outline:none;border-color:#2563eb}\n"
    "button{background:#2563eb;color:#fff;border:none;font-weight:600;cursor:pointer;margin-top:16px}\n"
    "button:active{background:#1d4ed8}\n"
    ".hint{font-size:12px;color:#888;margin:2px 0 0}\n"
    "#status{text-align:center;padding:8px;display:none;border-radius:6px;margin-bottom:12px}\n"
    ".btn-scan{background:#6b7280;margin-top:4px;padding:8px;font-size:14px}\n"
    "</style>\n"
    "</head><body>\n"
    "<h2>Claude Monitor</h2>\n"
    "<div id=\"status\"></div>\n"
    "<form method=\"POST\" action=\"/connect\" id=\"f\">\n"
    "<label for=\"ssid\">WiFi Network</label>\n"
    "<select name=\"ssid\" id=\"ssid\"><option value=\"\">Scanning...</option></select>\n"
    "<button type=\"button\" class=\"btn-scan\" onclick=\"scan()\">Rescan</button>\n"
    "\n"
    "<label for=\"password\">WiFi Password</label>\n"
    "<input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Leave empty for open networks\">\n"
    "\n"
    "<label for=\"refresh_tk\">Refresh Token</label>\n"
    "<p class=\"hint\">Run this in a terminal, then paste the result:</p>\n"
    "<div style=\"background:#1e293b;color:#e2e8f0;padding:10px;border-radius:6px;font-family:monospace;font-size:12px;word-break:break-all;margin:4px 0 8px;cursor:pointer\" onclick=\"navigator.clipboard.writeText(this.textContent)\">jq -r '.claudeAiOauth.refreshToken' ~/.claude/.credentials.json</div>\n"
    "<input type=\"text\" name=\"refresh_tk\" id=\"refresh_tk\" placeholder=\"Optional - can set later\">\n"
    "<p class=\"hint\">Tap the command above to copy it</p>\n"
    "\n"
    "<button type=\"submit\">Connect</button>\n"
    "</form>\n"
    "<script>\n"
    "function scan(){\n"
    "  var s=document.getElementById('ssid');\n"
    "  s.innerHTML='<option value=\"\">Scanning...</option>';\n"
    "  fetch('/scan').then(function(r){return r.json()}).then(function(nets){\n"
    "    if(!nets.length){s.innerHTML='<option value=\"\">No networks found</option>';return}\n"
    "    s.innerHTML='';\n"
    "    nets.sort(function(a,b){return b.rssi-a.rssi});\n"
    "    var seen={};\n"
    "    nets.forEach(function(n){\n"
    "      if(!n.ssid||seen[n.ssid])return;\n"
    "      seen[n.ssid]=1;\n"
    "      var o=document.createElement('option');\n"
    "      o.value=n.ssid;\n"
    "      o.textContent=n.ssid+' ('+n.rssi+' dBm)';\n"
    "      s.appendChild(o);\n"
    "    });\n"
    "  }).catch(function(){\n"
    "    s.innerHTML='<option value=\"\">Scan failed</option>';\n"
    "  });\n"
    "}\n"
    "scan();\n"
    "document.getElementById('f').onsubmit=function(e){\n"
    "  e.preventDefault();\n"
    "  var ssid=document.getElementById('ssid').value;\n"
    "  if(!ssid){\n"
    "    var st=document.getElementById('status');\n"
    "    st.style.display='block';st.style.background='#fee2e2';st.style.color='#b91c1c';\n"
    "    st.textContent='Please select a network';\n"
    "    return;\n"
    "  }\n"
    "  var fd=new URLSearchParams(new FormData(this));\n"
    "  fetch('/connect',{method:'POST',body:fd}).then(function(){\n"
    "    document.body.innerHTML='<div style=\"text-align:center;padding:60px 20px\"><h2>OK!</h2><p>Device will reboot and connect to your WiFi.</p></div>';\n"
    "  }).catch(function(){\n"
    "    document.body.innerHTML='<div style=\"text-align:center;padding:60px 20px\"><h2>Sent!</h2><p>Device should reboot shortly.</p></div>';\n"
    "  });\n"
    "  document.body.innerHTML='<div style=\"text-align:center;padding:60px 20px\"><h2>Connecting...</h2><p>Sending configuration...</p></div>';\n"
    "};\n"
    "</script>\n"
    "</body></html>\n";

