/* Auto-generated — do not edit */
static const char settings_html[] =
    "<!DOCTYPE html>\n"
    "<html><head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>Claude Watch</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:-apple-system,system-ui,sans-serif;background:#0f172a;color:#e2e8f0;max-width:480px;margin:0 auto;padding:16px}\n"
    "h2{text-align:center;margin-bottom:12px;font-size:20px}\n"
    "\n"
    "/* Tabs */\n"
    ".tabs{display:flex;gap:4px;margin-bottom:16px;border-bottom:2px solid #1e293b}\n"
    ".tab{flex:1;padding:10px;text-align:center;cursor:pointer;border-radius:6px 6px 0 0;background:#1e293b;color:#94a3b8;font-size:14px;font-weight:600;transition:all .2s}\n"
    ".tab.active{background:#2563eb;color:#fff}\n"
    ".panel{display:none}\n"
    ".panel.active{display:block}\n"
    "\n"
    "/* Toast */\n"
    ".toast{position:fixed;top:16px;left:50%;transform:translateX(-50%);padding:10px 20px;border-radius:6px;font-weight:600;display:none;z-index:99}\n"
    ".toast.ok{background:#d1fae5;color:#065f46}\n"
    ".toast.error{background:#fee2e2;color:#b91c1c}\n"
    "\n"
    "/* Forms */\n"
    "label{display:block;margin:12px 0 4px;font-weight:600;font-size:13px;color:#94a3b8}\n"
    "select,input,textarea{width:100%;padding:10px;border:1px solid #334155;border-radius:6px;font-size:14px;background:#1e293b;color:#e2e8f0}\n"
    "select:focus,input:focus{outline:none;border-color:#2563eb}\n"
    "button,.btn{display:block;width:100%;padding:10px;border:none;border-radius:6px;font-size:14px;font-weight:600;cursor:pointer;margin-top:12px;transition:background .2s}\n"
    ".btn-primary{background:#2563eb;color:#fff}\n"
    ".btn-primary:hover{background:#1d4ed8}\n"
    ".btn-danger{background:#dc2626;color:#fff}\n"
    ".btn-danger:hover{background:#b91c1c}\n"
    ".btn-secondary{background:#334155;color:#e2e8f0}\n"
    "\n"
    "/* Info bar */\n"
    ".info{background:#1e293b;padding:10px;border-radius:6px;font-size:13px;color:#94a3b8;margin-bottom:12px}\n"
    "\n"
    "/* Account */\n"
    ".auth-steps{font-size:14px;line-height:1.8}\n"
    ".auth-steps a{color:#60a5fa}\n"
    ".copy-link{font-size:12px;color:#64748b;cursor:pointer;margin-left:8px}\n"
    "\n"
    "/* Display config */\n"
    ".screen-row{display:flex;align-items:center;justify-content:space-between;padding:10px;background:#1e293b;border-radius:6px;margin-bottom:6px}\n"
    ".screen-toggle{display:flex;align-items:center;gap:8px;cursor:pointer;font-size:14px}\n"
    ".screen-toggle input{width:auto;margin:0}\n"
    ".screen-arrows{display:flex;gap:4px}\n"
    ".arr{width:32px;height:32px;border:1px solid #334155;border-radius:4px;background:#0f172a;color:#94a3b8;cursor:pointer;font-size:12px;padding:0}\n"
    ".arr:hover:not(:disabled){background:#334155;color:#fff}\n"
    ".arr:disabled{opacity:.3;cursor:default}\n"
    "\n"
    ".hint{font-size:12px;color:#64748b;margin-top:2px}\n"
    "</style>\n"
    "</head><body>\n"
    "\n"
    "<h2>Claude Watch</h2>\n"
    "<div class=\"toast\" id=\"toast\"></div>\n"
    "\n"
    "<div class=\"tabs\">\n"
    "  <div class=\"tab active\" data-panel=\"p-settings\">Settings</div>\n"
    "  <div class=\"tab\" data-panel=\"p-account\">Account</div>\n"
    "  <div class=\"tab\" data-panel=\"p-display\">Display</div>\n"
    "</div>\n"
    "\n"
    "<!-- Settings -->\n"
    "<div class=\"panel active\" id=\"p-settings\">\n"
    "  <div class=\"info\" id=\"wifi-info\">Loading...</div>\n"
    "  <form id=\"settings-form\">\n"
    "    <label for=\"ss\">WiFi SSID</label>\n"
    "    <input id=\"ss\" placeholder=\"Leave empty to keep current\">\n"
    "    <label for=\"pw\">WiFi Password</label>\n"
    "    <input type=\"password\" id=\"pw\" placeholder=\"Leave empty to keep current\">\n"
    "    <label for=\"tz\">Timezone</label>\n"
    "    <select id=\"tz\">\n"
    "      <option value=\"CET-1CEST,M3.5.0,M10.5.0/3\">Europe/Paris</option>\n"
    "      <option value=\"GMT0BST,M3.5.0/1,M10.5.0\">Europe/London</option>\n"
    "      <option value=\"EET-2EEST,M3.5.0/3,M10.5.0/4\">Europe/Helsinki</option>\n"
    "      <option value=\"EST5EDT,M3.2.0,M11.1.0\">US/Eastern</option>\n"
    "      <option value=\"CST6CDT,M3.2.0,M11.1.0\">US/Central</option>\n"
    "      <option value=\"MST7MDT,M3.2.0,M11.1.0\">US/Mountain</option>\n"
    "      <option value=\"PST8PDT,M3.2.0,M11.1.0\">US/Pacific</option>\n"
    "      <option value=\"JST-9\">Asia/Tokyo</option>\n"
    "      <option value=\"CST-8\">Asia/Shanghai</option>\n"
    "      <option value=\"IST-5:30\">Asia/Kolkata</option>\n"
    "      <option value=\"AEST-10AEDT,M10.1.0,M4.1.0/3\">Australia/Sydney</option>\n"
    "      <option value=\"UTC0\">UTC</option>\n"
    "    </select>\n"
    "    <label for=\"fi\">Fetch Interval</label>\n"
    "    <select id=\"fi\">\n"
    "      <option value=\"1\">1 min</option>\n"
    "      <option value=\"2\">2 min</option>\n"
    "      <option value=\"5\">5 min</option>\n"
    "      <option value=\"10\">10 min</option>\n"
    "      <option value=\"15\">15 min</option>\n"
    "      <option value=\"30\">30 min</option>\n"
    "    </select>\n"
    "    <button type=\"submit\" class=\"btn btn-primary\">Save Settings</button>\n"
    "  </form>\n"
    "  <button class=\"btn btn-danger\" id=\"btn-wifi-reset\">Reset WiFi &amp; Reboot</button>\n"
    "</div>\n"
    "\n"
    "<!-- Account -->\n"
    "<div class=\"panel\" id=\"p-account\">\n"
    "  <div class=\"info\" id=\"token-status\">Loading...</div>\n"
    "  <div class=\"auth-steps\">\n"
    "    <p>1. <a href=\"#\" id=\"auth-link\" target=\"_blank\" rel=\"noreferrer noopener\">Login with Anthropic</a>\n"
    "       <a href=\"#\" id=\"copy-auth-url\" class=\"copy-link\">Copy URL</a></p>\n"
    "    <p>2. Paste the authorization code below:</p>\n"
    "  </div>\n"
    "  <input id=\"auth-code\" placeholder=\"Paste authorization code\">\n"
    "  <button class=\"btn btn-primary\" id=\"btn-authorize\">Authorize</button>\n"
    "</div>\n"
    "\n"
    "<!-- Display -->\n"
    "<div class=\"panel\" id=\"p-display\">\n"
    "  <p class=\"hint\" style=\"margin-bottom:12px\">Enable/disable screens and set their order. Tap arrows to reorder.</p>\n"
    "  <div id=\"screen-list\"></div>\n"
    "  <button class=\"btn btn-primary\" id=\"btn-save-display\">Save Display Config</button>\n"
    "</div>\n"
    "\n"
    "<script>(()=>{function l(){document.querySelectorAll(\".tab\").forEach(t=>{t.addEventListener(\"click\",()=>{document.querySelectorAll(\".tab\").forEach(e=>e.classList.remove(\"active\")),document.querySelectorAll(\".panel\").forEach(e=>e.classList.remove(\"active\")),t.classList.add(\"active\"),document.getElementById(t.dataset.panel).classList.add(\"active\")})})}function a(t,e=!1){let n=document.getElementById(\"toast\");n.textContent=t,n.className=\"toast \"+(e?\"error\":\"ok\"),n.style.display=\"block\",setTimeout(()=>n.style.display=\"none\",2500)}async function d(){try{let e=await(await fetch(\"/api/config\")).json();document.getElementById(\"tz\").value=e.timezone||\"CET-1CEST,M3.5.0,M10.5.0/3\",document.getElementById(\"fi\").value=e.fetch_interval||\"10\",document.getElementById(\"wifi-info\").textContent=`WiFi: ${e.ssid} | IP: ${e.ip}`,document.getElementById(\"token-status\").textContent=`Token: ${e.token_status}`;let n=document.getElementById(\"auth-link\");n.href=e.auth_url}catch{a(\"Failed to load config\",!0)}}function r(){document.getElementById(\"settings-form\").addEventListener(\"submit\",async t=>{t.preventDefault();let e=new URLSearchParams({ssid:document.getElementById(\"ss\").value,password:document.getElementById(\"pw\").value,timezone:document.getElementById(\"tz\").value,fetch_int:document.getElementById(\"fi\").value});try{await fetch(\"/api/config\",{method:\"POST\",body:e}),a(\"Settings saved!\")}catch{a(\"Save failed\",!0)}}),document.getElementById(\"btn-wifi-reset\").addEventListener(\"click\",async()=>{confirm(\"Reset WiFi and reboot?\")&&(await fetch(\"/api/wifi-reset\",{method:\"POST\"}),document.body.innerHTML=\"<h2>Rebooting...</h2>\")})}function u(){document.getElementById(\"btn-authorize\").addEventListener(\"click\",async()=>{let t=document.getElementById(\"auth-code\").value.trim();if(!t){a(\"Paste the code first\",!0);return}try{(await(await fetch(\"/api/oauth/exchange\",{method:\"POST\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body:`code=${encodeURIComponent(t)}`})).json()).ok?(a(\"Authorized!\"),d()):a(\"Authorization failed\",!0)}catch{a(\"Authorization failed\",!0)}}),document.getElementById(\"copy-auth-url\").addEventListener(\"click\",t=>{t.preventDefault();let e=document.getElementById(\"auth-link\").href;navigator.clipboard.writeText(e).then(()=>{t.target.textContent=\"Copied!\",setTimeout(()=>t.target.textContent=\"Copy URL\",2e3)})})}var o=[];async function m(){try{o=(await(await fetch(\"/api/display\")).json()).screens,s()}catch{a(\"Failed to load display config\",!0)}}function s(){let t=document.getElementById(\"screen-list\");t.innerHTML=\"\",o.forEach((e,n)=>{let c=document.createElement(\"div\");c.className=\"screen-row\",c.innerHTML=`\n"
    "      <label class=\"screen-toggle\">\n"
    "        <input type=\"checkbox\" ${e.enabled?\"checked\":\"\"} data-idx=\"${n}\">\n"
    "        <span>${e.name}</span>\n"
    "      </label>\n"
    "      <div class=\"screen-arrows\">\n"
    "        <button class=\"arr\" data-dir=\"up\" data-idx=\"${n}\" ${n===0?\"disabled\":\"\"}>&#9650;</button>\n"
    "        <button class=\"arr\" data-dir=\"down\" data-idx=\"${n}\" ${n===o.length-1?\"disabled\":\"\"}>&#9660;</button>\n"
    "      </div>\n"
    "    `,t.appendChild(c)}),t.querySelectorAll(\"input[type=checkbox]\").forEach(e=>{e.addEventListener(\"change\",()=>{o[Number(e.dataset.idx)].enabled=e.checked})}),t.querySelectorAll(\".arr\").forEach(e=>{e.addEventListener(\"click\",()=>{let n=Number(e.dataset.idx),c=e.dataset.dir===\"up\"?-1:1,i=n+c;[o[n],o[i]]=[o[i],o[n]],s()})})}function y(){document.getElementById(\"btn-save-display\").addEventListener(\"click\",async()=>{let t=o.map(e=>`${e.id}:${e.enabled?1:0}`).join(\",\");try{await fetch(\"/api/display\",{method:\"POST\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body:`screens=${encodeURIComponent(t)}`}),a(\"Display config saved!\")}catch{a(\"Save failed\",!0)}}),m()}document.addEventListener(\"DOMContentLoaded\",()=>{l(),r(),u(),y(),d()});})();\n"
    "</script>\n"
    "</body></html>\n"
;
