[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf

monitor_speed = 115200

; SPI pins for the round display (GC9A01)
; XIAO ESP32-S3 pinout for the round display base
build_flags =
    -DCONFIG_LV_COLOR_DEPTH=16
